### ISSUE TITLE
Uncaught TypeError: Calendar is not a constructor

### ISSUE THREAD

**Issue by mohsenSy** [nhnent/tui.calendar#173]
## Version
latest version on master

## Development Environment
Vivalid Browser, Ubuntu 18.04

## Current Behavior
I am getting this error in the console `Uncaught TypeError: Calendar is not a constructor` and no calendar.

I am trying to use the calendar in my Django project, I downloaded `tui-calendar.css` and `tui-calendar.js` and included them in my page.

```js
var Calendar = tui.Calendar;

var calendar = new Calendar('#calendar', {
});
```

## Expected Behavior
No error should appear in the console

**Comment by mohsenSy** [comment]
Solved by following instructions [here](http://ui.toast.com/tui-calendar/)

**Comment by zviredler** [comment]
If using Jquery-
This solved the problem

$('#calendar').tuiCalendar({
  defaultView: 'month',
  taskView: true,
  template: {
    monthGridHeader: function(model) {
      var date = new Date(model.date);
      var template = '<span class="tui-full-calendar-weekday-grid-date">' + date.getDate() + '</span>';
      return template;
    }
  }
});

**Comment by Gobliins** [comment]
Problem is not solved, i also get this error. also with this instructions 

> Solved by following instructions here

import Calendar from 'tui-calendar'; /* ES6 */
import "tui-calendar/dist/tui-calendar.css";

const calendar = new Calendar('#calendar', {
  defaultView: 'month',
});

**Comment by alanmrochadeveloper** [comment]
> Problem is not solved, i also get this error even with this instructions
> 
> > Solved by following instructions here
> 
> ```
> import "tui-calendar/dist/tui-calendar.css";
> 
> const calendar = new Calendar('#calendar', {
>   defaultView: 'month',
> });```
> ```

me too, how to solve it?

**Comment by alirezadigi** [comment]
same issue , any ideas?
tried all of the previous solutions ...
